### ISSUE TITLE
Move to Requests org

### ISSUE THREAD

**Issue by kennethreitz** [requests/toolbelt#187]
Just an idea :)

✨🍰✨

**Comment by sigmavirus24** [comment]
@Lukasa thoughts on giving this a more "official" stamp?

**Comment by Lukasa** [comment]
No particular preference either way. Can't hurt though: I'm increasingly frustrated with working on projects in personal namespaces on Github, as they lack the ability to share the most important administrative tools.

**Comment by sigmavirus24** [comment]
Anyone have an objection to renaming the repo itself to `toolbelt` so that it's URL is `github.com/requests/toolbelt`?

**Comment by kennethreitz** [comment]
+100!
