### ISSUE TITLE
Is there a reason for leaking the original content in MultipartDecoder ?

### ISSUE THREAD

**Issue by tzickel** [requests/toolbelt#220]
https://github.com/requests/toolbelt/blob/6d74296f0f267d9e06ba7828585dac61276d4e2b/requests_toolbelt/multipart/decoder.py#L105

I think this is a bug, but I'm not sure so I'm asking here.

Is there any reason to tie the scope of the MultipartDecoder object to it's input content ? looking at the code it doesn't even use it after the constructor is done.

Think about some very large content being passed in, after being split to parts, you now have twice the memory being consumed till you free the MultipartDecoder (even if you already deleted the original request object)..

**Comment by sigmavirus24** [comment]
We use it here:

https://github.com/requests/toolbelt/blob/6d74296f0f267d9e06ba7828585dac61276d4e2b/requests_toolbelt/multipart/decoder.py#L151

It could be passed into that method, absolutely, but this also allows for debugging

**Comment by tzickel** [comment]
So maybe a flag in the constructor if to retain it or not ? (i.e. clear it in the end or not), with default to clear ? (Or document this), think about passing a few gigabytes to it, you have now *2 gigabytes hanging over without knowing.

**Comment by sigmavirus24** [comment]
> Think about passing a few gigabytes to it, you have now *2 gigabytes hanging over without knowing.

Right, I get that entirely. I'm wondering if it makes sense to just drop it altogether. I hate classes whose attributes are conditional based on a flag passed to the initializer.

I'm happy to merge a PR that just drops the `.content` attribute and does the right thing here. 🎉
