### ISSUE TITLE
MultipartEncoderMonitor's callback documentation is wrong

### ISSUE THREAD

**Issue by DavidVentura** [requests/toolbelt#223]
The callback docs say 
http://toolbelt.readthedocs.io/en/latest/uploading-data.html#requests_toolbelt.multipart.encoder.MultipartEncoderMonitor

```python
def callback(encoder, bytes_read):
```

same with the comments in the code:

https://github.com/requests/toolbelt/blob/master/requests_toolbelt/multipart/encoder.py#L342

but the actual callback only sends an instance of `self`
https://github.com/requests/toolbelt/blob/master/requests_toolbelt/multipart/encoder.py#L403

**Comment by sigmavirus24** [comment]
I'd happy accept a PR that corrects the documentation
