### ISSUE TITLE
requests-toolbelt uses abcs from collections instead of from collections.abc

### ISSUE THREAD

**Issue by Achimh3011** [requests/toolbelt#228]
Warning message:

    site-packages/requests_toolbelt/_compat.py:11:  DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

Version:

    requests-toolbelt==0.8.0

**Comment by sigmavirus24** [comment]
I'd be happy to merge a PR that fixes this without breaking backwards compatibility

**Comment by jaraco** [comment]
I'm still getting this warning. Would love to see a release with the fix.

**Comment by jaraco** [comment]
This issue bit me again. Maybe consider a release with the fix? Can I help?
