### ISSUE TITLE
Update version in PyPi

### ISSUE THREAD

**Issue by VladimirPodolyan** [requests/toolbelt#233]
Pls update current version in [PyPi](https://pypi.org/project/requests-toolbelt/)

**Comment by ssbarnea** [comment]
In addition to this the manifest should be included to point to github as finding the source code and issue tracker is currently not easy.  

Nowdays PYPI is able to display lots of useful information in the sidebar: open bugs, open PRs, stars.

**Comment by sigmavirus24** [comment]
Released 0.9.0.

I'll happily merge a PR that improves the metadata
