### ISSUE TITLE
Bug with MultipartDecoder(content, contentType)

### ISSUE THREAD

**Issue by markvivanco** [requests/toolbelt#236]
I am trying to parse Multipart data but its throwing an error.  The data is coming from a file upload via dropzone.js framework to AWS Lambda.  I've extracted the relevant data to a small sample to view the bug.  

```python
import sys
sys.path.append('vendored')

from requests_toolbelt.multipart import decoder

content = '------WebKitFormBoundaryYm5AaYtV0p30lK7t\r\nContent-Disposition: form-data; name="file"; filename="testheader.csv"\r\nContent-Type: text/csv\r\n\r\nhdr1,hdr2,hdr3\nval1,val2,val3\r\n------WebKitFormBoundaryYm5AaYtV0p30lK7t--\r\n'
contentType = 'multipart/form-data; boundary=----WebKitFormBoundaryYm5AaYtV0p30lK7t'
multipart_data = decoder.MultipartDecoder(content, contentType)

print("Multipart:", multipart_data)

for part in multipart_data.parts:
	print("Part.Content:", part.content)
	print("Part.headers:", part.headers)
	print("Part.Text:", part.text)
```
The error being thrown is:
Traceback (most recent call last):
  File "/Users/me/Code/Tests/build/dev/testMisc.py", line 8, in <module>
    multipart_data = decoder.MultipartDecoder(body, contentType)
  File "vendored/requests_toolbelt/multipart/decoder.py", line 113, in __init__
    self._parse_body()
  File "vendored/requests_toolbelt/multipart/decoder.py", line 151, in _parse_body
    parts = self.content.split(b''.join((b'\r\n', boundary)))
TypeError: must be str or None, not bytes

**Comment by sigmavirus24** [comment]
Looks like you're passing text but the Decoder wants bytes. For example, you should be doing

```py
content = b'------WebKitFormBoundary...'
```

This is not a bug in the decoder. This was how it was intended to be used.

**Comment by markvivanco** [comment]
I had tried it with str and byte strings and both throw errors just in different places.

```python
import sys
sys.path.append('vendored')

from requests_toolbelt.multipart import decoder

content = b'------WebKitFormBoundaryYm5AaYtV0p30lK7t\r\nContent-Disposition: form-data; name="file"; filename="testheader.csv"\r\nContent-Type: text/csv\r\n\r\nhdr1,hdr2,hdr3\nval1,val2,val3\r\n------WebKitFormBoundaryYm5AaYtV0p30lK7t--\r\n'
contentType = b'multipart/form-data; boundary=----WebKitFormBoundaryYm5AaYtV0p30lK7t'
multipart_data = decoder.MultipartDecoder(content, contentType)

print("Multipart:", multipart_data)

for part in multipart_data.parts:
	print("Part.Content:", part.content)
	print("Part.headers:", part.headers)
	print("Part.Text:", part.text)
```
  File "vendored/requests_toolbelt/multipart/decoder.py", line 112, in __init__
    self._find_boundary()
  File "vendored/requests_toolbelt/multipart/decoder.py", line 116, in _find_boundary
    ct_info = tuple(x.strip() for x in self.content_type.split(';'))
TypeError: a bytes-like object is required, not 'str'
