### ISSUE TITLE
MultipartDecoder for streaming response

### ISSUE THREAD

**Issue by farleylai** [requests/toolbelt#287]
It seems like the `MultipartDecoder` splits the response content into parts.
What if the response is a potentially infinite stream and each part has a separate Content-Length?
If not supported, any plan to support that soon?

**Comment by sigmavirus24** [comment]
Given that the decoder doesn't handling streaming responses right now, the answer is no to both.

**Comment by farleylai** [comment]
Got it. Any update would be appreciated.
