### ISSUE TITLE
Usage of SourceAddressAdapter to create multiple source ip

### ISSUE THREAD

**Issue by kaushik853** [requests/toolbelt#291]
Hi,
Can you tell how can i test it with multiple source ip address . Something i tried like
```python
from requests_toolbelt.adapters import source
session = PACSession(pac)
list_source_ip_and_url = [("10.129.xx.yy", "https://google.com"), ("10.189.yy.xx", "https://random.com/Surveyor.Web/")]
responses = []
try:
    for source_ip, url in list_source_ip_and_url:
        new_source = source.SourceAddressAdapter(source_ip)
        session.mount('http://', new_source)
        session.mount('https://', new_source)
        responses.append(session.get(url))
    print(responses)
except Exception as e:
    print(e)
```
I am getting error like:
HTTPSConnectionPool(host='google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x033D5547>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
Looks like im hitting some requests module error.

**Comment by sigmavirus24** [comment]
The important part here is 

```
[WinError 10049] The requested address is not valid in its context'
```

That's the Windows operating system reporting the error that prevents Requests and urllib3 from opening a new socket.

Further, `PACSession` doesn't look like a normal Requests session and thus we can't guarantee compatibility.

**Comment by kaushik853** [comment]
The ip which i want to assign is not in any interface of my machine and also belong to different ip address class itself. Also i dont have a rights to change the ip in my machine. Is that one of the reasons?

**Comment by sigmavirus24** [comment]
> Is that one of the reasons?

That sounds plausible. I'm not a windows socket error expert though so it could be that or it could be something else. I really don't know and can't offer help. [StackOverflow](https://stackoverflow.com) should be able to help you with this though. That's where this should have been raised to start with.
