### ISSUE TITLE
MultipartEncoder cannot terminate large file sending early

### ISSUE THREAD

**Issue by crabtreej** [requests/toolbelt#292]
Issue: The MultipartEncoder module will continue sending the entirety of a file after the receiver has already attempted to terminate the request. Specifically, this problem is occurring on toolbelt 0.9.1, and the request is being sent to a Django server running Django 3.0.5. 

This isn't an issue for smaller files, because Django will just read in the entire file and drop it. However, my use case is sending files up to several GB in size, and this will cause Django to crash with a Memory Error. This also means that the response describing why the upload was dropped is never sent, and will occasionally make the requests module hang unless the Django server is completely killed. This is also an issue for mid-sized files (say, 800mb) because MultipartEncoder will waste time sending the entire file when an error response was immediately returned.

It may be that this is expected behavior for MultipartEncoder, but I've found that other tools for sending files as multi-part encoded (e.g. curl) will terminate immediately upon receiving a response from Django, and not overwhelm the server. I would expect that at least in the case of an HTTP error being sent back to the sender during transmission that curl's behavior is more desirable.

A minimal example reproducing the error is below. Additionally, to see that curl does not have this issue, you can run:
`curl -k -F file=@test.txt http://localhost:8000/upload`
The upload will immediately terminate instead of sending the entire file, and receive the response from Django.

**Views.py**
```
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

@csrf_exempt
@require_POST
def upload(request):
    return HttpResponse("Done!", status=400)
```

**Multipart Upload**
```
import requests
from requests_toolbelt.multipart.encoder import MultipartEncoder

def upload_file(file_name):
    f_handle = open(file_name, 'rb')
    m = MultipartEncoder({'file': (file_name, f_handle, 'raw')})
    res = requests.post('http://localhost:8000/upload', data=m, headers={'Content-Type': m.content_type})
    res.raise_for_status()
```

**Comment by sigmavirus24** [comment]
This is not a problem with the multipart encoder, it's an issue with requests
