### ISSUE TITLE
Threading - rate limits for APIs that limit number request/second

### ISSUE THREAD

**Issue by leeprevost** [requests/toolbelt#298]
For your mode for multi-threding requests, I'm using the toolbelt this way:

```
`   p=pool.Pool.from_urls(urls, request_kwargs=request_kwargs)
    p.join_all()
    print("Retrieving {} new URLs from fmp".format(len(urls)))
    responses = [(response.url, response.json()) for response in p.responses()]
    no_response = [pull_ticker_from_url(tup[0]) for tup in responses if not tup[1]]
    responses = [tup[1] for tup in responses if _is_valid(tup[1])]
    exceptions = [(pull_ticker_from_url(exc.url), exc.message) for exc in p.exceptions()]
    #no_response = [response.url for response in p.responses() if not response.json()]
    payload = {"responses": responses,
               "exceptions": exceptions,
               "no_response": no_response}
    return payload`
```

Is there a way to rate limit for a website that requires limits of reuqests per second (eg. 20 requests/second)?   I could do that with a requests decorator like this one:
[https://github.com/tomasbasham/ratelimit](url)

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
