### ISSUE TITLE
new release please?

### ISSUE THREAD

**Issue by pnemade** [requests/toolbelt#322]
Hi,
I saw there is no upstream release since more than one year. Are there any plans to make a new release tarball? It will help distributions to use all recent commit fixes since 0.9.1 tarball release.
Thanks

**Comment by mbBRCM** [comment]
Upvoted, a new release would be great :)

**Comment by LiuJinghao** [comment]
Upvoted

**Comment by kkirsche** [comment]
Since the requests project was moved under psf, I'd recommend asking them about potentially transferring ownership of this project to them. They may have more traction to make something like this happen

**Comment by pquentin** [comment]
I released 0.10.0 today.
