### ISSUE TITLE
Documentation about StreamingIterator unclear

### ISSUE THREAD

**Issue by fireattack** [requests/toolbelt#349]
I was trying to use this today this way:

```python
import requests
from requests_toolbelt.streaming_iterator import StreamingIterator

data = b'someverylongdata'
size = len(data)

def gen():
    offset = 0
    while True:
        if offset < size:
            yield data[offset:offset+1024]
        else:
            break
        offset += 1024

streamer = StreamingIterator(size, gen)

r = requests.post('https://httpbin.org/post', data=streamer)
print(r.json())
```

And it didn't work. Error: "'function' object is not an iterator".

After reading the code, it looks like `gen` has to be an object that has a `read()` (or, it has to be a file object). A generic generator function isn't going to work. But this isn't clear in [the documentation](https://toolbelt.readthedocs.io/en/latest/uploading-data.html#streaming-data-from-a-generator) especially when it says `generator = some_function()  # Create your generator`.

Especially consider that the `gen()` actually works in plain requests:
```py
r = requests.post('https://httpbin.org/post', data=gen())
print(r.json())
```

So I expect that if you drop it into StreamingIterator it should work.

**Comment by sigmavirus24** [comment]
You're not passing a generator, you're passing a function. Did you try

```py
streamer = StreamingIterator(size, gen())
```

(Note, calling gen to create a generator rather than passing a function)

**Comment by fireattack** [comment]
Well, that's embarrassing. You're absolutely right. 

Sorry for the rookie mistake, and thanks for the help.
