### ISSUE TITLE
Making releases with changelog

### ISSUE THREAD

**Issue by leszekhanusz** [requests/toolbelt#362]
I'm investigating [issue 412 of gql](https://github.com/graphql-python/gql/issues/412) and was interested to know if there was any breaking change with version 1.0
Usually you should find this information in the [releases tab of GitHub](https://github.com/requests/toolbelt/releases) but it does not seem to be there.

Could you please make releases with changelogs so that users could know what has changed between versions?

Thanks!

**Comment by leszekhanusz** [comment]
That's not a nice answer. The least you could do is point me to where I can find that changelog. Looking for changelog in your doc does not find anything and you don't have a `CHANGELOG.rst` file either.

I'm also a maintainer (of gql) and it's really not a lot of work to do it.

Where can I find this changelog?

**Comment by sigmavirus24** [comment]
> That's not a nice answer.

If you think someone telling you no is not nice, I'm not sure what else to do for you. Not accepting no as an answer is a very good way to end up violating another person's boundaries and is a large red flag.
