### ISSUE TITLE
Add GzipAdapter

### ISSUE THREAD

**Issue by ysangkok** [requests/toolbelt#60]
Would it be possible to add the GzipAdapter from here: https://github.com/kennethreitz/requests/issues/1753 ?
##

**Comment by Lukasa** [comment]
+1, why not?

**Comment by ysangkok** [comment]
There is one issue, I believe: GzipFile includes the headers that `Content-Encoding: gzip` do not use.

**Comment by ysangkok** [comment]
But luckily, there is `[zlib.compressobj](https://docs.python.org/3/library/zlib.html#zlib.compressobj)`.

**Comment by sigmavirus24** [comment]
The adapter that @ionrock wrote is imcomplete since it doesn't update the `Content-Length` header. Further it's unclear to me how to handle some corner cases and the proper header to set would be `Transfer-Encoding`

**Comment by sigmavirus24** [comment]
Also technically that adapter is @ionrock's copyright. But I'm +1 on this if we can sort out the corner cases

**Comment by ionrock** [comment]
Feel free to consider it BSD licensed. I think I wrote it directly in that comment, so it obviously needs to be fleshed out and tested.

**Comment by sigmavirus24** [comment]
@ionrock by all means please do. So here are the concerns I didn't want to write out on my phone last night:

1. I'm 90% sure this adapter would imply a header of `Transfer-Encoding: gzip` in the simplest case, not `Content-Encoding: gzip`.
1. In the simplest case, I think we need to update the `Content-Length` header.
1. There are two other cases that we need to hande beyond the simplest:

   - File-like objects that we should be streaming
   - Generators that are being used for chunked uploads

For file-like objects, we will need to check for a `Content-Length` header. 

- If there is none, that means requests couldn't determine a length, so the parent adapter (HTTPAdapter) will want to handle it like a chunked upload (so we'll handle that like a generator). 
- If there is a `Content-Length` header, we'll have to assume the user wants us to gzip the streamed request. That means we have to create a temporary file with the gzip data so we can update the `Content-Length`. I assume this is where `GzipFile` would come in handy.

For chunked uploads

- We'll want to provide our own generator, something like:

```py
(zlib.compressobj(chunk) for chunk in chunked_upload)
```

But I'll have to read the RFCs to see if there's any tricks to doing that properly. I'm honestly uncertain. The above is just a guess.

**Comment by ysangkok** [comment]
Closing since Gzip has since been superseded by faster/better compression methods.
