### ISSUE TITLE
MultipartEncoder does not handle int/long/float arguments

### ISSUE THREAD

**Issue by cpnielsen** [requests/toolbelt#99]
This is not critical, but in keeping parity with requests I thought it would be worth mentioning.

If you pass in an integer or float argument as a parameter to send, the `encode_with` function fails (https://github.com/sigmavirus24/requests-toolbelt/blob/master/requests_toolbelt/multipart/encoder.py#L385) as it assumes that all input is either a string or None/bytes (in which cases it does not attempt to further encode).

Sample code to reproduce:

```
from requests_toolbelt.multipart import encoder

enc = encoder.MultipartEncoder({
    'test': 1  # alternatively try "1.0" or "100L" for similar errors
})
```

The base `requests` library accepts these values (and just encodes them as strings), even if the library could reasonably expect strings only (or file handles).
##

**Comment by sigmavirus24** [comment]
I guess I need to document that we only ever expect string or bytes objects. We have no intention of supporting bare number types like requests does.

**Comment by xblitz** [comment]
I don't think you have to "support" other types..  instead of assuming that it is a string.. we could just get the string representation of the object whatever it is.. even if its a complex object that has a __str__ defined it would work

I think probably just putting a  str(data) instead at this line: https://github.com/sigmavirus24/requests-toolbelt/blob/master/requests_toolbelt/multipart/encoder.py#L449  would work...

**Comment by sigmavirus24** [comment]
@xblitz that's meant to be a IO like object that returns bytes not unicode. There's a significant difference on Python 3. What we need is some complex logic around what we think we can accurately handle for the user. Floats/ints (and on Python 2.7, longs) are some types. I don't think we can accurately decipher what the user wants us to do with lists and tuples though.

For more context, on Python 3 if you have something like

```py
some_bytes = b'foobarbogus'
```

And you call `str()` on that you'll get `"b'foobarbogus'"` which is absolutely not what the user wants. So we have to be *very* careful with what we call `str` on.
